export {
  DEFAULT_SOURCE_DIFF_PATHS,
  DEFAULT_TEST_DIFF_PATHS,
  MAX_CHANGED_LINES,
  MAX_DIFF_BYTES,
  MAX_DIFF_FILES,
  DiffPolicyError,
  containsCredentialPattern,
  canonicalDiffPath,
  parseSourceAuthoringDiff,
  parseTestAuthoringDiff,
  parseUnifiedDiff,
  type DiffOperation,
  type DiffPolicyOptions,
  type ParsedDiffFile,
  type ParsedDiffHunk,
  type ParsedUnifiedDiff,
} from "./diff-policy.js";
export {
  DEFAULT_M5_TOOLING_INPUTS,
  DEFAULT_PROJECTION_INPUTS,
  DEFAULT_SOURCE_REVISION_INPUTS,
  computeM5ProjectionRevision,
  computeM5ToolingRevision,
  computeToolingRevision,
  computeNoGitSourceRevision,
  createSourceProjection,
  removeSourceProjection,
  verifyM5ToolingSnapshot,
  verifySourceProjection,
  type SourceProjection,
  type SourceSnapshotOptions,
} from "./snapshot.js";
export {
  applyParsedDiff,
  combineAuthoringDiffs,
  copyProjectionToWorkspace,
  createSandboxControl,
  type ApplyDiffOptions,
  type AppliedDiff,
} from "./patch-apply.js";
export {
  classifySandboxObservation,
  isCandidatePass,
  isExpectedFailure,
  type SandboxObservation,
} from "./result-classifier.js";
export {
  DOCKER_IMAGE_PATTERN,
  DOCKER_NETWORK_POLICY,
  DOCKER_PULL_POLICY,
  DOCKER_RESOURCE_LIMITS,
  FIXED_SANDBOX_COMMANDS,
  checkDockerPrerequisites,
  clearSandboxExport,
  runDockerCandidate,
  runDockerProcess,
  type DockerProcessRequest,
  type DockerProcessResult,
  type DockerProcessRunner,
  type DockerRunOptions,
  type DockerPrerequisiteResult,
  type DockerRunResult,
  type ExportedSandboxFile,
  type SandboxCommandId,
} from "./docker-runner.js";
